language: go
go:
    - 1.12
    - tip
services:
    - postgresql
env:
    - >-
      ADMIN_KEY=myAdminApiKey
      DB_HOST=127.0.0.1
      DB_PORT=5432
      DB_USER=postgres
      DB_NAME=dumbwaiter
      DB_PASS=postgres
before_script:
    - psql -c 'create database dumbwaiter;' -U postgres
    - go fmt ./...
script:
    - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
after_success:
    - bash <(curl -s https://codecov.io/bash)
