language: python
python: 3.7
cache: pip
install: pip install -r requirements.txt
services:
    - postgresql
env:
    - >-
      DJANGO_SETTINGS_MODULE=server.settings.base
      DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/dumbwaiter
before_script:
    - black --check .
    - flake8 .
    - mypy .
    - psql -c 'create database dumbwaiter;' -U postgres
script:
    - python manage.py collectstatic --noinput
after_success:
    - codecov
