language: go
go:
    - release
services:
    - postgresql
env:
    - >-
      ADMIN_KEY=myAdminApiKey
      DB_HOST=127.0.0.1
      DB_PORT=5432
      DB_USER=postgres
      DB_NAME=dumbwaiter
      DB_PASS=postgres
before_script:
    - psql -c 'create database dumbwaiter;' -U postgres
    - go fmt ./...
script:
    - go test -v ./...
after_success:
    - codecov
