version: '3'

services:
    nginx:
        image: nginx
        ports:
            - "3000:80"
        volumes:
            - .:/code
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - react

    django:
        build: .
        restart: always
        env_file: .env
        command: bash docker-entrypoint.sh
        depends_on:
            - db
        links:
            - db

    react:
        build: .
        restart: always
        command: npm start
        depends_on:
            - django
        links:
            - django

    db:
        image: postgres
        env_file: .env
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:

